name: "functionalSelfTest"
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: getNextAttemptNumber
        uses: cardinalby/js-eval-action@master
        env:
          STEP_SIZE: 2
        with:
          data: '8'
          expression: "parseInt(inputs.data) + parseInt(env.STEP_SIZE)"

      - name: Check getNextAttemptNumber result
        if: steps.getNextAttemptNumber.outputs.result != '10'
        run: exit 1

      - id: checkNewVersion
        uses: cardinalby/js-eval-action@master
        env:
          OLD_VERSION: 1.2.3
          NEW_VERSION: 1.3.0
        with:
          expression: |
            ({ 
              greater: semver.gte(env.NEW_VERSION, env.OLD_VERSION), 
              compatible: semver.major(env.NEW_VERSION) === semver.major(env.OLD_VERSION)
            })
          extractOutputs: 'true'

      - name: Check checkNewVersion result
        if: steps.checkNewVersion.outputs.greater != 'true' || steps.checkNewVersion.outputs.compatible != 'true'
        run: exit 1

      - id: jsonExample
        uses: cardinalby/js-eval-action@master
        env:
          MY_VAR: '{"a": "hello", "b": "hell"}'
        with:
          jsonEnvs: MY_VAR
          expression: "env.MY_VAR.a.indexOf(env.MY_VAR.b) !== -1"

      - name: Check jsonExample result
        if: steps.jsonExample.outputs.result != 'true'
        run: exit 1

      - id: getDefaultBranch
        uses: cardinalby/js-eval-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          expression: |
            (await octokit.rest.repos.get({
              owner: context.repo.owner, 
              repo: context.repo.repo
            })).data.default_branch

      - name: Check getDefaultBranch result
        if: steps.jsonExample.outputs.result != 'master'
        run: exit 1

      - id: readYamlExample
        uses: cardinalby/js-eval-action@v1
        with:
          expression: 'yaml.parse((await fs.readFile("action.yml")).toString()).name'

      - name: Check getDefaultBranch result
        if: steps.jsonExample.outputs.result != 'js-eval-action'
        run: exit 1